name: 'App Store Connect Token'
description: 'Get token for App Store Connect'
branding:
  icon: 'smartphone'  
  color: 'blue'
inputs:
  app-id:
    description: 'App Store application identifier'
    required: false
    default: ''
  key-id:
    description: 'Private key ID from App Store Connect'
    required: false
    default: ''
  issuer-id:
    description: 'Issuer ID from the API Keys page in App Store Connect'
    required: false
    default: ''
  private-key-p8-path:
    description: 'Private key file downloaded from the API Keys page in App Store Connect (*.p8 file)'
    required: false
    default: ''
  private-key-p8-base64:
    description: 'Private key downloaded from the API Keys page in App Store Connect (*.p8 file) in Base64 format'
    required: false
    default: ''
  private-key-raw:
    description: 'Raw private key downloaded from the API Keys page in App Store Connect'
    required: false
    default: ''
outputs:
  token:
    description: 'App Store Connect token'
runs:
  using: 'node16'
  main: './src/index.js'
